### ISSUE TITLE
支持中文账号

### ISSUE THREAD

**Issue by poly000** [DEGINX/Fuck_Qingjiao-2-Class.com-#2]
```
Traceback (most recent call last):
  File "D:\workdir\2-class.py", line 208, in <module>
    Piliang()
  File "D:\workdir\2-class.py", line 204, in Piliang
    Function(sheet1.row_values(i)[0], str(sheet1.row_values(i)[1])[0:8])
  File "D:\workdir\2-class.py", line 20, in Function
    Login(account, password, reqtoken, sid)
  File "D:\workdir\2-class.py", line 45, in Login
    conn.request("POST", "/api/user/login", payload, headers)
  File "C:\Users\WIN-PC\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\WIN-PC\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1300, in _send_request
    body = _encode(body, 'body')
  File "C:\Users\WIN-PC\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 164, in _encode
    raise UnicodeEncodeError(
UnicodeEncodeError: 'latin-1' codec can't encode character '\u5f20' in position 12: Body ('张') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

```

**Comment by hanbings** [comment]
不考虑特殊情况 且相关活动已基本结束 关闭此Issues
